env:
  browser: true
  es2021: true
  node: true
  jest: true
extends:
  - mta
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 13
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {}
ignorePatterns:
  - node_modules/*
  - src/modules/pbjs/*
  - '*.md'
